# Generated by Django 4.0.2 on 2022-02-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('CPF', models.TextField(max_length=14, verbose_name='CPF')),
                ('Telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('tipo', models.CharField(choices=[('VS', 'Visitante'), ('FC', 'Funcionário')], default='VS', max_length=2)),
            ],
        ),
    ]
