# Generated by Django 4.0.2 on 2022-02-18 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_rename_author_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('CPF', models.TextField(max_length=14, verbose_name='CPF')),
                ('Telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('hora_entrada', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('hora_saida', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
