# Generated by Django 4.0.2 on 2022-02-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_remove_visitante_id_visitante_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='hora_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
