# Generated by Django 4.0.2 on 2022-02-18 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_alter_visitante_hora_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='hora_entrada',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Horário de Entrada'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='hora_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de Saída'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='tipo',
            field=models.CharField(choices=[('VS', 'Visitante'), ('MR', 'Morador')], default='VS', max_length=2, verbose_name='Tipo'),
        ),
    ]
