# Generated by Django 4.0.2 on 2022-02-18 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0006_alter_visitante_hora_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('CPF', models.TextField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF')),
                ('Nome_Completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('Endereco', models.CharField(max_length=100, verbose_name='Endereço completo')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('Telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('hora_entrada', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Horário de Entrada')),
                ('hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Horário de Saída')),
            ],
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='visitante',
            name='CPF',
            field=models.TextField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='placa',
            field=models.CharField(max_length=7, verbose_name='Placa'),
        ),
    ]
