# Generated by Django 4.0.2 on 2022-02-18 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0007_morador_remove_visitante_tipo_alter_visitante_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moradores',
            fields=[
                ('CPF', models.TextField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome_Completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=4, verbose_name='Número')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('hora_entrada', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Horário de Entrada')),
                ('hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Horário de Saída')),
            ],
        ),
        migrations.DeleteModel(
            name='Morador',
        ),
        migrations.RenameField(
            model_name='visitante',
            old_name='Nome_Completo',
            new_name='nome_Completo',
        ),
        migrations.RenameField(
            model_name='visitante',
            old_name='Telefone',
            new_name='telefone',
        ),
    ]
