# Generated by Django 3.2.7 on 2022-03-08 14:16

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0010_auto_20220304_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morador',
            options={'ordering': ['endereco', 'nome_completo'], 'verbose_name_plural': 'Morador'},
        ),
        migrations.AlterModelOptions(
            name='visitante',
            options={'ordering': ['nome_completo'], 'verbose_name_plural': 'Visitante'},
        ),
        migrations.AlterField(
            model_name='morador',
            name='CPF',
            field=cpf_field.models.CPFField(max_length=14, primary_key=True, serialize=False, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='CPF',
            field=cpf_field.models.CPFField(max_length=14, primary_key=True, serialize=False, verbose_name='cpf'),
        ),
    ]
