# Generated by Django 3.2.7 on 2022-03-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0012_auto_20220308_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='editable_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitante',
            name='editable_password',
            field=models.BooleanField(default=False),
        ),
    ]
