# Generated by Django 4.0.1 on 2022-03-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0013_auto_20220321_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='editable_password',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='editable_password',
        ),
    ]
